"use client";
import React, { useState } from 'react';
import { Hash, Copy, Check } from 'lucide-react';

const PasswordHashGenerator = () => {
  const [password, setPassword] = useState('dey123456');
  const [hash, setHash] = useState('');
  const [copied, setCopied] = useState(false);

  const generateHash = async () => {
    try {
      // This would normally be done on the backend, but for testing we can use a simple approach
      // In a real scenario, you'd call a backend endpoint to generate the hash
      setHash('Generating hash...');
      
      // For now, we'll show a placeholder - the actual hash should be generated by the backend
      setHash('$2b$12$... (Use backend to generate proper hash)');
    } catch (error) {
      setHash('Error generating hash');
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(hash);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed top-4 left-4 bg-white border border-gray-200 rounded-lg shadow-lg p-4 max-w-sm z-50">
      <div className="flex items-center gap-2 mb-3">
        <Hash className="w-4 h-4 text-blue-500" />
        <h3 className="text-sm font-medium text-gray-900">Password Hash Generator</h3>
      </div>

      <div className="space-y-3">
        <div>
          <label className="block text-xs font-medium text-gray-700 mb-1">
            Password:
          </label>
          <input
            type="text"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            className="w-full px-3 py-2 text-sm border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-blue-500"
            placeholder="Enter password"
          />
        </div>

        <button
          onClick={generateHash}
          className="w-full px-3 py-2 bg-blue-600 text-white text-sm rounded hover:bg-blue-700 transition-colors"
        >
          Generate Hash
        </button>

        {hash && (
          <div className="space-y-2">
            <label className="block text-xs font-medium text-gray-700">
              Generated Hash:
            </label>
            <div className="flex items-center gap-2">
              <input
                type="text"
                value={hash}
                readOnly
                className="flex-1 px-3 py-2 text-xs border border-gray-300 rounded bg-gray-50"
              />
              <button
                onClick={copyToClipboard}
                className="p-2 text-gray-400 hover:text-gray-600"
                title="Copy to clipboard"
              >
                {copied ? <Check className="w-3 h-3 text-green-500" /> : <Copy className="w-3 h-3" />}
              </button>
            </div>
          </div>
        )}

        <div className="text-xs text-gray-500">
          <div className="font-medium mb-1">Note:</div>
          <div>• Use backend to generate proper bcrypt hash</div>
          <div>• Hash should start with $2b$12$</div>
          <div>• For testing: dey123456</div>
        </div>
      </div>
    </div>
  );
};

export default PasswordHashGenerator;
